In [1]:
import numpy as np
import pandas as pd

In [71]:
# Create the State Action Reward Matrix

R = pd.read_excel('Maze_upd.xlsx',header=None)

In [72]:
R = np.matrix(R)
R

matrix([[ -1,   0,  -1, ...,  -1,  -1,  -1],
        [  0,  -1,  -1, ...,  -1,  -1,  -1],
        [ -1,  -1,  -1, ...,  -1,  -1,  -1],
        ...,
        [ -1,  -1,  -1, ...,  -1,  -1,  -1],
        [ -1,  -1,  -1, ...,  -1,  -1,  -1],
        [ -1,  -1,  -1, ...,  -1,  -1, 100]])

In [73]:
# Initialize the Q matrix with zeros

Q = np.zeros([50,50])

In [57]:
Q

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [74]:
# Set Gamma parameter

gamma = 0.7

In [59]:
# Initialize state for the mouse ( We will later make this selection random)

initial_state = 0

In [75]:
# Create a custom function that returns all available actions in the state passed as an argument

def avl_actions(state):
  current_state_row = R[state,]
  av_act = np.where(current_state_row >= 0)[1]
  return av_act

In [61]:
np.where(R[2,] >= 0)[1]

array([5, 6])

In [62]:
# Get the available actions in current state = 2

available_act = avl_actions(initial_state)

In [63]:
available_act

array([1])

In [76]:
# Next , we construct a function which chooses a random action to be performed within the range of all avl actions


def sample_next_action(available_actions_range):
  next_action = int(np.random.choice(available_actions_range,1))
  return next_action

In [65]:
action = sample_next_action(available_act)
action

1

In [77]:
# Now, we update the Q matrix according to the path selected using the Q learning algorithm formula

def update(current_state,action,gamma):
  max_index = np.where(Q[action,] == np.max(Q[action,]))[0]

  if max_index.shape[0] > 1:
    max_index = int(np.random.choice(max_index,1))

  else:
    max_index = int(max_index)

  max_value = Q[action,max_index]

  # Q-learning formula
  Q[current_state,action] = R[current_state,action] + gamma*max_value

In [78]:
# Update the Q matrix
update(initial_state,action,gamma)

In [79]:
Q

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [28]:
state=np.random.randint(0,9)
state

2

In [80]:
for i in range(0,100000):
  state=np.random.randint(0,49)
  available_act = avl_actions(state)
  action = sample_next_action(available_act)
  update(state,action,gamma)


In [81]:
Q

array([[0.        , 0.23263051, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.16284136, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [86]:
Q[27]

array([0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       4.0353607, 8.23543  , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       ])

In [87]:
current_state = 0
steps = [current_state]

while current_state != 49:
  next_step_index = np.where(Q[current_state,] == np.max(Q[current_state,]))[0]

  if next_step_index.shape[0] > 1:
    next_step_index = int(np.random.choice(next_step_index, 1))

  else:
    next_step_index = int(next_step_index)

  steps.append(next_step_index)
  current_state = next_step_index
  print(current_state)


print("The selected path:")
print(steps)

1
4
12
5
2
6
13
25
42
27
43
29
15
31
16
32
45
49
The selected path:
[0, 1, 4, 12, 5, 2, 6, 13, 25, 42, 27, 43, 29, 15, 31, 16, 32, 45, 49]
