In [1]:
import numpy as np
import pandas as pd

In [2]:
# Create the State Action Reward Matrix

R = pd.read_csv('mousehunt-rewardmatrix.csv',header=None)

In [3]:
R = np.matrix(R)
R

matrix([[ -1,  -1,  -1,   0,  -1,  -1,  -1,  -1,  -1,  -1],
        [ -1,  -1,   0,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
        [ -1,   0,  -1,  -1,  -1,   0,  -1,  -1,  -1, 100],
        [  0,  -1,  -1,  -1,   0,  -1,   0,  -1,  -1,  -1],
        [ -1,  -1,  -1,   0,  -1,   0,  -1,   0,  -1,  -1],
        [ -1,  -1,   0,  -1,   0,  -1,  -1,  -1,  -1,  -1],
        [ -1,  -1,  -1,   0,  -1,  -1,  -1,  -1,  -1,  -1],
        [ -1,  -1,  -1,  -1,   0,  -1,  -1,  -1,   0, 100],
        [ -1,  -1,  -1,  -1,  -1,  -1,  -1,   0,  -1,  -1],
        [ -1,  -1,   0,  -1,  -1,  -1,  -1,   0,  -1, 100]])

In [4]:
# Initialize the Q matrix with zeros

Q = np.zeros([10,10])

In [5]:
Q

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
# Set Gamma parameter

gamma = 0.7

In [7]:
# Initialize state for the mouse ( We will later make this selection random)

initial_state = 2

In [8]:
# Create a custom function that returns all available actions in the state passed as an argument

def avl_actions(state):
  current_state_row = R[state,]
  av_act = np.where(current_state_row >= 0)[1]
  return av_act

In [9]:
np.where(R[2,] >= 0)[1]

array([1, 5, 9])

In [10]:
# Get the available actions in current state = 2

available_act = avl_actions(initial_state)

In [11]:
available_act

array([1, 5, 9])

In [16]:
# Next , we construct a function which chooses a random action to be performed within the range of all avl actions


def sample_next_action(available_actions_range):
  next_action = int(np.random.choice(available_actions_range,1))
  return next_action

In [21]:
action = sample_next_action(available_act)
action

9

In [23]:
np.where(Q[action,] == np.max(Q[action,]))[0] #this is only for updating Q-matrix

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# Now, we update the Q matrix according to the path selected using the Q learning algorithm formula

def update(current_state,action,gamma):
  max_index = np.where(Q[action,] == np.max(Q[action,]))[0]

  if max_index.shape[0] > 1:
    max_index = int(np.random.choice(max_index,1))

  else:
    max_index = int(max_index)

  max_value = Q[action,max_index]

  # Q-learning formula
  Q[current_state,action] = R[current_state,action] + gamma*max_value

In [25]:
# Update the Q matrix
update(initial_state,action,gamma)

In [26]:
Q

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 100.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]])

In [36]:
state=np.random.randint(0,9)
state

6

In [41]:
for i in range(0,1000):
  state=np.random.randint(0,Q.shape[0])
  available_act = avl_actions(state)
  action = sample_next_action(available_act)
  update(state,action,gamma)


In [42]:
Q

array([[  0.        ,   0.        ,   0.        , 114.33333278,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        , 233.33333254,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ],
       [  0.        , 163.33333171,   0.        ,   0.        ,
          0.        , 163.33333101,   0.        ,   0.        ,
          0.        , 333.33333254],
       [ 80.03333254,   0.        ,   0.        ,   0.        ,
        163.33333254,   0.        ,  80.03333171,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , 114.3333322 ,
          0.        , 163.33333294,   0.        , 233.3333322 ,
          0.        ,   0.        ],
       [  0.        ,   0.        , 233.33333278,   0.        ,
        163.33333254,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ],
       [  

In [44]:
current_state = 0
steps = [current_state]

while current_state != 9:
  next_step_index = np.where(Q[current_state,] == np.max(Q[current_state,]))[0]

  if next_step_index.shape[0] > 1:
    next_step_index = int(np.random.choice(next_step_index, 1))

  else:
    next_step_index = int(next_step_index)

  steps.append(next_step_index)
  current_state = next_step_index


print("The selected path:")
print(steps)

The selected path:
[0, 3, 4, 7, 9]
